services:
  ionic:
    container_name: nectar-frontend-technical-test-v1-ionic
    build: .
    ports:
      - "8100:8100"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ionic serve --host 0.0.0.0 --port 8100 --ssl
